version: "3.8"

services:

  cookbook:
    build: ./cookbook
    ports:
      - "8080:8080"

  cookbook-client:
    build: ./cookbook-client
    ports:
      - "3000:3000"
    volumes:
      - ./cookbook-client/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - cookbook
